### ISSUE TITLE
Further options for autoCommit relevant flags

### ISSUE THREAD

**Issue by kevinprotoss** [kambing86/kafkajs-stream#2]
Hi,

thanks great for the work. It's a perfect lib for using kafkajs together with stream. However, could you provide more options to set autoCommit relevant flags. Just like the configs of kafkajs:

[Manual committing](https://kafka.js.org/docs/consuming#manual-commits)

```javascript
consumer.run({
    autoCommit: false,
    eachMessage: async ({ topic, partition, message }) => {
        // Process the message somehow
    },
})
```

We want to consume the kafka without offset commit. If possible, sincerely thousand thanks.

Best regards,
Kevin

**Comment by kambing86** [comment]
@kevinprotoss the `runConfig` is added in, please get the latest version from npm
